#ifndef DOUBLECLIQUE_SERVER_PROFILER_METRICS_H
#define DOUBLECLIQUE_SERVER_PROFILER_METRICS_H

typedef enum {
    PROF_SERVER_REQUESTS_PROCESSED = 0,
    PROF_SERVER_POLL_SLOT_TOTAL,
    PROF_SERVER_POLL_KEY_COPY,
    PROF_SERVER_POLL_KEY_HASH,
    PROF_SERVER_PUT_TOTAL,
    PROF_SERVER_PUT_READ_COPY,
    PROF_SERVER_PUT_HASH_VERIFY,
    PROF_SERVER_PUT_INDEX_LOOKUP,
    PROF_SERVER_PUT_RETRY_INDEX_LOOKUP,
    PROF_SERVER_PUT_FIND_FREE_INDEX_SLOT,
    PROF_SERVER_PUT_ALLOC,
    PROF_SERVER_PUT_GC_ENQUEUE,
    PROF_SERVER_PUT_GC_GET_CLOCK,
    PROF_SERVER_PUT_GC_ENQUEUE_CALL,
    PROF_SERVER_PUT_INSERT,
    PROF_SERVER_PUT_MARK_HEADER_UNUSED,
    PROF_SERVER_PUT_ACK,
    PROF_SERVER_GET1_ACK_TOTAL,
    PROF_SERVER_GET1_COPY_BUCKET,
    PROF_SERVER_GET1_COPY_BUCKET_PLAIN,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_SCAN,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_COPY_TO_ACK,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_MATCH_CHECK,
    PROF_SERVER_GET1_WRITEBACK_COPY,
    PROF_SERVER_GET1_ACK_FINALIZE,
    PROF_SERVER_GET2_ACK_TOTAL,
    PROF_SERVER_GET2_COPY,

    SERVER_PROF_METRIC_COUNT
} server_perf_metric_id_t;

#endif //DOUBLECLIQUE_SERVER_PROFILER_METRICS_H
