#ifndef DOUBLECLIQUE_PROFILER_H
#define DOUBLECLIQUE_PROFILER_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    PROF_CLIENT_ACK_GET_QUEUE_WAIT = 0,
    PROF_CLIENT_ACK_HEADER_SLOT_WAIT,
    PROF_CLIENT_ACK_DATA_SPACE_WAIT,
    PROF_CLIENT_ACK_ACK_SPACE_WAIT,
    PROF_CLIENT_ACK_ALLOC_TOTAL,
    PROF_CLIENT_SEND_HEADER,
    PROF_CLIENT_PUT_COPY,
    PROF_CLIENT_PUT_HASH,
    PROF_CLIENT_PUT_TOTAL,
    PROF_CLIENT_PUT_ACK_POLL,
    PROF_CLIENT_GET2_COPY,
    PROF_CLIENT_GET2_HASH,
    PROF_CLIENT_GET2_PHASE1_TOTAL,
    PROF_CLIENT_GET2_ACK_PHASE1_POLL,
    PROF_CLIENT_GET2_ACK_PHASE2_POLL,
    PROF_CLIENT_GET1_KEY_HASH,
    PROF_CLIENT_GET1_INDEX_FETCH_DISPATCH,
    PROF_CLIENT_GET1_INDEX_CALLBACK,
    PROF_CLIENT_GET1_PREFERRED_FETCH_CB,
    PROF_CLIENT_GET1_CONTINGENCY_PREP,
    PROF_CLIENT_GET1_CONTINGENCY_CB,
    PROF_CLIENT_GET1_TOTAL,

    PROF_SERVER_REQUESTS_PROCESSED,
    PROF_SERVER_POLL_SLOT_TOTAL,
    PROF_SERVER_POLL_KEY_COPY,
    PROF_SERVER_POLL_KEY_HASH,
    PROF_SERVER_PUT_TOTAL,
    PROF_SERVER_PUT_READ_COPY,
    PROF_SERVER_PUT_HASH_VERIFY,
    PROF_SERVER_PUT_INDEX_LOOKUP,
    PROF_SERVER_PUT_ALLOC,
    PROF_SERVER_PUT_INSERT,
    PROF_SERVER_PUT_ACK,
    PROF_SERVER_GET1_ACK_TOTAL,
    PROF_SERVER_GET1_COPY_BUCKET,
    PROF_SERVER_GET1_WRITEBACK_COPY,
    PROF_SERVER_GET2_ACK_TOTAL,
    PROF_SERVER_GET2_COPY,

    PROF_METRIC_COUNT
} perf_metric_id_t;

uint64_t perf_now_ns(void);
void perf_record_ns(perf_metric_id_t id, uint64_t duration_ns);
void perf_record_ns_bytes(perf_metric_id_t id, uint64_t duration_ns, uint64_t bytes);
void perf_increment(perf_metric_id_t id, uint64_t amount);
void perf_reset_all(void);
void perf_print_client_report(void);
void perf_print_server_report(bool reset_after_print);

#endif //DOUBLECLIQUE_PROFILER_H
