#ifndef DOUBLECLIQUE_PROFILER_H
#define DOUBLECLIQUE_PROFILER_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    PROF_CLIENT_ACK_GET_QUEUE_WAIT = 0,
    PROF_CLIENT_ACK_HEADER_SLOT_WAIT,
    PROF_CLIENT_ACK_DATA_SPACE_WAIT,
    PROF_CLIENT_ACK_ACK_SPACE_WAIT,
    PROF_CLIENT_ACK_ALLOC_TOTAL,
    PROF_CLIENT_ACK_REPLICA_RESET,
    PROF_CLIENT_ACK_PROMISE_ALLOC,
    PROF_CLIENT_ACK_SLOT_PREP,
    PROF_CLIENT_ACK_COMMIT,
    PROF_CLIENT_SEND_HEADER,
    PROF_CLIENT_PUT_COPY,
    PROF_CLIENT_PUT_HASH,
    PROF_CLIENT_PUT_ACK_SLOT_ACQUIRE,
    PROF_CLIENT_PUT_HASH_BUF_ALLOC,
    PROF_CLIENT_PUT_SEND_HEADER,
    PROF_CLIENT_PUT_TOTAL,
    PROF_CLIENT_PUT_ACK_POLL,
    PROF_CLIENT_PUT_ACK_POLL_SCAN,
    PROF_CLIENT_PUT_ACK_POLL_TIMEOUT_CHECK,
    PROF_CLIENT_PUT_ACK_POLL_RESULT,
    PROF_CLIENT_GET2_COPY,
    PROF_CLIENT_GET2_HASH,
    PROF_CLIENT_GET2_ACK_SLOT_ACQUIRE,
    PROF_CLIENT_GET2_HASH_BUF_ALLOC,
    PROF_CLIENT_GET2_SEND_PHASE1,
    PROF_CLIENT_GET2_PHASE1_TOTAL,
    PROF_CLIENT_GET2_ACK_PHASE1_POLL,
    PROF_CLIENT_GET2_ACK_PHASE1_SCAN_ACKS,
    PROF_CLIENT_GET2_ACK_PHASE1_BUILD_CANDIDATES,
    PROF_CLIENT_GET2_ACK_PHASE1_FILTER_QUORUM,
    PROF_CLIENT_GET2_ACK_PHASE1_FASTPATH_VERIFY,
    PROF_CLIENT_GET2_ACK_PHASE1_SHIP_PHASE2,
    PROF_CLIENT_GET2_ACK_PHASE1_TIMEOUT_CHECK,
    PROF_CLIENT_GET2_ACK_PHASE1_RESULT,
    PROF_CLIENT_GET2_ACK_PHASE2_POLL,
    PROF_CLIENT_GET2_ACK_PHASE2_TIMEOUT_CHECK,
    PROF_CLIENT_GET2_ACK_PHASE2_VERIFY_AND_COPY,
    PROF_CLIENT_GET2_ACK_PHASE2_RESULT,
    PROF_CLIENT_GET1_KEY_HASH,
    PROF_CLIENT_GET1_INDEX_FETCH_DISPATCH,
    PROF_CLIENT_GET1_INDEX_CALLBACK,
    PROF_CLIENT_GET1_PREFERRED_FETCH_CB,
    PROF_CLIENT_GET1_CONTINGENCY_PREP,
    PROF_CLIENT_GET1_CONTINGENCY_CB,
    PROF_CLIENT_GET1_TOTAL,

    PROF_SERVER_REQUESTS_PROCESSED,
    PROF_SERVER_POLL_SLOT_TOTAL,
    PROF_SERVER_POLL_KEY_COPY,
    PROF_SERVER_POLL_KEY_HASH,
    PROF_SERVER_PUT_TOTAL,
    PROF_SERVER_PUT_READ_COPY,
    PROF_SERVER_PUT_HASH_VERIFY,
    PROF_SERVER_PUT_INDEX_LOOKUP,
    PROF_SERVER_PUT_RETRY_INDEX_LOOKUP,
    PROF_SERVER_PUT_FIND_FREE_INDEX_SLOT,
    PROF_SERVER_PUT_ALLOC,
    PROF_SERVER_PUT_GC_ENQUEUE,
    PROF_SERVER_PUT_GC_GET_CLOCK,
    PROF_SERVER_PUT_GC_ENQUEUE_CALL,
    PROF_SERVER_PUT_INSERT,
    PROF_SERVER_PUT_MARK_HEADER_UNUSED,
    PROF_SERVER_PUT_ACK,
    PROF_SERVER_GET1_ACK_TOTAL,
    PROF_SERVER_GET1_COPY_BUCKET,
    PROF_SERVER_GET1_COPY_BUCKET_PLAIN,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_SCAN,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_COPY_TO_ACK,
    PROF_SERVER_GET1_COPY_BUCKET_WRITEBACK_MATCH_CHECK,
    PROF_SERVER_GET1_WRITEBACK_COPY,
    PROF_SERVER_GET1_ACK_FINALIZE,
    PROF_SERVER_GET2_ACK_TOTAL,
    PROF_SERVER_GET2_COPY,

    PROF_METRIC_COUNT
} perf_metric_id_t;

uint64_t perf_now_ns(void);
void perf_record_ns(perf_metric_id_t id, uint64_t duration_ns);
void perf_record_ns_bytes(perf_metric_id_t id, uint64_t duration_ns, uint64_t bytes);
void perf_increment(perf_metric_id_t id, uint64_t amount);
void perf_reset_all(void);
void perf_print_client_report(void);
void perf_print_server_report(bool reset_after_print);

#endif //DOUBLECLIQUE_PROFILER_H
